# Generated by Django 3.2.16 on 2023-08-10 17:05

import apps.language.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_language_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='imagen',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.language.models.lenguaje_thumbnail_directory),
        ),
    ]
