# Generated by Django 3.2.16 on 2023-06-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('blog', '0004_auto_20230622_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='post',
            name='languages',
            field=models.ManyToManyField(related_name='posts', to='language.Language'),
        ),
    ]
