# Generated by Django 3.2.16 on 2023-08-15 04:57

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230622_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
